"""Student revision chatbot routes."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from flask import Flask, abort, jsonify, redirect, render_template, request, url_for, current_app

import web_ai
import web_context
import web_db
import web_markdown
import web_uploads


def register(app: Flask) -> None:
    def gemini_reply(*, user: dict[str, Any], chat_id: int, user_text: str, use_web: bool = False) -> str:
        return web_ai.gemini_reply(
            client=current_app.config.get("GEMINI_CLIENT"),
            types=current_app.config.get("GEMINI_TYPES"),
            model_name=current_app.config.get("GEMINI_MODEL_NAME"),
            user=user,
            chat_id=chat_id,
            user_text=user_text,
            use_web=bool(use_web),
        )

    def gemini_reply_with_upload(
        *,
        user: dict[str, Any],
        chat_id: int,
        user_text: str,
        use_web: bool,
        upload_text: str | None,
        upload_image_bytes: bytes | None,
        upload_image_mime: str | None,
    ) -> str:
        return web_ai.gemini_reply(
            client=current_app.config.get("GEMINI_CLIENT"),
            types=current_app.config.get("GEMINI_TYPES"),
            model_name=current_app.config.get("GEMINI_MODEL_NAME"),
            user=user,
            chat_id=chat_id,
            user_text=user_text,
            use_web=bool(use_web),
            upload_text=upload_text,
            upload_image_bytes=upload_image_bytes,
            upload_image_mime=upload_image_mime,
        )

    def _to_bool(v: Any) -> bool:
        if isinstance(v, bool):
            return v
        s = str(v or "").strip().lower()
        return s in {"1", "true", "yes", "y", "on"}

    @app.route("/revision")
    def revision_home():
        user = web_context.role_required("student")
        chats = web_db.list_chats(user_id=int(user["id"]), chat_type="revision")
        
        if not chats:
            chat_id = web_db.create_chat(user_id=int(user["id"]), title="Revision: General", chat_type="revision")
            return redirect(url_for("revision", chat_id=chat_id))
        
        return redirect(url_for("revision", chat_id=int(chats[0]["id"])))

    @app.route("/revision/new", methods=["POST"])
    def revision_new():
        user = web_context.role_required("student")
        subject = (request.form.get("subject") or "General").strip()
        topics = (request.form.get("topics") or "").strip()
        study_guide = (request.form.get("study_guide") or "").strip()
        student_form_raw = (request.form.get("student_form") or "").strip()

        chat_id_raw = (request.form.get("chat_id") or "").strip()
        schedule_item_id_raw = (request.form.get("schedule_item_id") or "").strip()

        # If the client already has a chat_id for this session, just open it.
        if chat_id_raw:
            try:
                existing = web_db.get_chat(chat_id=int(chat_id_raw), user_id=int(user["id"]))
            except Exception:
                existing = None
            if existing and str(existing.get("chat_type") or "") == "revision":
                return redirect(url_for("revision", chat_id=int(existing["id"])))

        # If the client knows the schedule session, try to reuse its cached revision thread.
        schedule_item_id_int = None
        if schedule_item_id_raw:
            try:
                schedule_item_id_int = int(schedule_item_id_raw)
            except Exception:
                schedule_item_id_int = None

        if schedule_item_id_int is not None and schedule_item_id_int > 0:
            # Schedule-linked revision: create/reuse chat quickly; full guide is generated by the revision page (init API).
            cached = None
            try:
                cached = web_db.get_revision_session_for_user(user_id=int(user["id"]), schedule_item_id=schedule_item_id_int)
            except Exception:
                cached = None

            if cached and cached.get("chat_id"):
                try:
                    existing = web_db.get_chat(chat_id=int(cached.get("chat_id") or 0), user_id=int(user["id"]))
                except Exception:
                    existing = None
                if existing and str(existing.get("chat_type") or "") == "revision":
                    return redirect(url_for("revision", chat_id=int(existing["id"])))

            schedule_item = web_db.get_schedule_item_for_user(user_id=int(user["id"]), schedule_item_id=schedule_item_id_int)
            if schedule_item:
                subject = str(schedule_item.get("subject") or subject or "General").strip() or "General"

            title = f"Revision: {subject}"
            chat_id = web_db.create_chat(user_id=int(user["id"]), title=title, chat_type="revision")

            # Link chat to this schedule session (topics were precomputed at schedule generation time).
            try:
                if cached:
                    web_db.upsert_revision_session(
                        user_id=int(user["id"]),
                        schedule_item_id=schedule_item_id_int,
                        assignment_id=(int(cached.get("assignment_id")) if cached.get("assignment_id") is not None else None),
                        subject=str(cached.get("subject") or subject),
                        scope=(str(cached.get("scope") or "").strip() or None),
                        duration_minutes=(int(cached.get("duration_minutes")) if cached.get("duration_minutes") is not None else None),
                        session_count=int(cached.get("session_count") or 1),
                        session_index=int(cached.get("session_index") or 1),
                        topics=list(cached.get("topics") or []),
                        all_topics=list(cached.get("all_topics") or []),
                        study_guide_md=(str(cached.get("study_guide_md") or "").strip() or None),
                        chat_id=chat_id,
                    )
                else:
                    # Fallback: create a minimal row so init can run.
                    web_db.upsert_revision_session(
                        user_id=int(user["id"]),
                        schedule_item_id=schedule_item_id_int,
                        assignment_id=None,
                        subject=subject,
                        scope=None,
                        duration_minutes=None,
                        session_count=1,
                        session_index=1,
                        topics=[],
                        all_topics=[],
                        study_guide_md=None,
                        chat_id=chat_id,
                    )
            except Exception:
                current_app.logger.exception("Failed to link revision session to chat")

            return redirect(url_for("revision", chat_id=chat_id))
        
        title = f"Revision: {subject}"
        chat_id = web_db.create_chat(user_id=int(user["id"]), title=title, chat_type="revision")
        
        # Add initial assistant message with revision context
        if topics or study_guide:
            initial_parts = []
            
            if topics:
                initial_parts.append(f"Let's review {subject}. Topics to cover:\n{topics}")
            
            if study_guide:
                if topics:
                    initial_parts.append(f"\n\nStudy Guide:\n{study_guide}")
                else:
                    initial_parts.append(f"Let's review {subject}.\n\nStudy Guide:\n{study_guide}")
            
            initial_msg = "\n".join(initial_parts)
            # Add as assistant message so it appears from the bot
            web_db.add_message(chat_id=chat_id, role="assistant", content=initial_msg)
        
        # If this revision was launched from a schedule session, persist a mapping so it reopens instantly next time.
        if schedule_item_id_int is not None and schedule_item_id_int > 0:
            def _topics_to_list(s: str) -> list[str]:
                out: list[str] = []
                for line in (s or "").splitlines():
                    t = line.strip()
                    if not t:
                        continue
                    if t.startswith(('-', '•', '*')):
                        t = t[1:].strip()
                    if t:
                        out.append(t)
                return out

            try:
                web_db.upsert_revision_session(
                    user_id=int(user["id"]),
                    schedule_item_id=schedule_item_id_int,
                    assignment_id=None,
                    subject=subject,
                    scope=None,
                    duration_minutes=None,
                    session_count=1,
                    session_index=1,
                    topics=_topics_to_list(topics),
                    all_topics=_topics_to_list(topics),
                    study_guide_md=study_guide,
                    chat_id=chat_id,
                )
            except Exception:
                current_app.logger.exception("Failed to persist revision session mapping")

        return redirect(url_for("revision", chat_id=chat_id))

    @app.route("/revision/<int:chat_id>", methods=["GET", "POST"])
    def revision(chat_id: int):
        user = web_context.role_required("student")
        chat_row = web_db.get_chat(chat_id=chat_id, user_id=int(user["id"]))
        if not chat_row:
            abort(404)

        if request.method == "POST":
            text = (request.form.get("message") or "").strip()
            use_web = _to_bool(request.form.get("use_web"))
            if text:
                web_db.add_message(chat_id=chat_id, role="user", content=text)

                try:
                    reply = gemini_reply(user=user, chat_id=chat_id, user_text=text, use_web=use_web)
                except Exception as e:
                    current_app.logger.exception("Gemini reply failed")
                    reply = f"Sorry — chat failed: {e}"
                web_db.add_message(chat_id=chat_id, role="assistant", content=reply)

            return redirect(url_for("revision", chat_id=chat_id))

        chats = web_db.list_chats(user_id=int(user["id"]), chat_type="revision")
        
        messages = web_db.list_messages(chat_id=chat_id, limit=250)
        has_assistant = any((m.get("role") == "assistant") for m in (messages or []))
        for m in messages:
            if m["role"] == "assistant":
                m["content_html"] = web_markdown.render_markdown(m.get("content") or "")

        auto_init = False
        if not has_assistant:
            try:
                sess = web_db.get_revision_session_for_user_by_chat_id(user_id=int(user["id"]), chat_id=chat_id)
            except Exception:
                sess = None
            if sess:
                auto_init = True

        # Study timer is only available for schedule-linked Study with me sessions.
        study_timer_enabled = False
        try:
            sess2 = web_db.get_revision_session_for_user_by_chat_id(user_id=int(user["id"]), chat_id=chat_id)
        except Exception:
            sess2 = None
        if sess2:
            try:
                study_timer_enabled = int(sess2.get("schedule_item_id") or 0) > 0
            except Exception:
                study_timer_enabled = False

        try:
            user_coins = int(user.get("coins") or 0)
        except Exception:
            user_coins = 0

        return render_template(
            "revision.html",
            chats=chats,
            active_chat_id=chat_id,
            messages=messages,
            chat_title=chat_row.get("title", "Revision"),
            auto_init=auto_init,
            study_timer_enabled=study_timer_enabled,
            user_coins=user_coins,
        )

    @app.route("/api/revision/<int:chat_id>/init", methods=["POST"])
    def api_revision_init(chat_id: int):
        """Generate the initial study guide for a schedule-linked revision chat."""
        user = web_context.role_required("student")
        chat_row = web_db.get_chat(chat_id=chat_id, user_id=int(user["id"]))
        if not chat_row:
            return jsonify(ok=False, error="Chat not found"), 404

        # If the chat already has an assistant message, don't regenerate.
        try:
            msgs = web_db.list_messages(chat_id=chat_id, limit=10)
        except Exception:
            msgs = []
        if any((m.get("role") == "assistant") for m in (msgs or [])):
            return jsonify(ok=True, skipped=True)

        sess = None
        try:
            sess = web_db.get_revision_session_for_user_by_chat_id(user_id=int(user["id"]), chat_id=chat_id)
        except Exception:
            sess = None
        if not sess:
            return jsonify(ok=True, skipped=True)

        subject = str(sess.get("subject") or "General").strip() or "General"
        topics_list = list(sess.get("topics") or [])
        if not topics_list:
            scope_fallback = str(sess.get("scope") or "").strip()
            topics_list = [scope_fallback] if scope_fallback else [subject]

        cached_guide = str(sess.get("study_guide_md") or "").strip()
        if cached_guide:
            topics_text = "\n".join([f"- {t}" for t in topics_list if str(t).strip()])
            initial_msg = (
                f"Let's review {subject}. Topics to cover:\n{topics_text}\n\nStudy Guide:\n{cached_guide}".strip()
                if topics_text.strip()
                else f"Let's review {subject}.\n\nStudy Guide:\n{cached_guide}".strip()
            )
            web_db.add_message(chat_id=chat_id, role="assistant", content=initial_msg)
            return jsonify(ok=True, reply=initial_msg, reply_html=web_markdown.render_markdown(initial_msg), cached=True)

        try:
            duration_minutes = int(sess.get("duration_minutes") or 0) or 120
        except Exception:
            duration_minutes = 120

        # Student form from class_level (e.g., "5A" -> 5)
        class_level = str(user.get("class_level") or "")
        sf = 5
        for ch in class_level:
            if ch.isdigit():
                try:
                    sf = int(ch)
                except Exception:
                    sf = 5
                break

        # Scope is the session's topics only.
        scope = "\n".join([f"- {t}" for t in topics_list if str(t).strip()]) or subject

        from web_study_guide import generate_study_guide

        try:
            result = generate_study_guide(
                student_form=sf,
                subject=subject,
                scope=scope,
                duration_minutes=duration_minutes,
                session_count=1,
                session_index=1,
                session_schedule=None,
                client=current_app.config.get("GEMINI_CLIENT"),
                types=current_app.config.get("GEMINI_TYPES"),
                model_name=current_app.config.get("GEMINI_MODEL_NAME"),
            )
        except Exception as e:
            current_app.logger.exception("Failed to generate initial revision guide")
            return jsonify(ok=False, error=str(e)), 500

        guide_md = str(result.get("study_guide") or "").strip()
        topics_now = list(result.get("topics") or topics_list)
        all_topics = list(result.get("all_topics") or [])

        topics_text = "\n".join([f"- {t}" for t in topics_now if str(t).strip()])
        initial_parts: list[str] = []
        if topics_text.strip():
            initial_parts.append(f"Let's review {subject}. Topics to cover:\n{topics_text}")
        if guide_md:
            if topics_text.strip():
                initial_parts.append(f"\n\nStudy Guide:\n{guide_md}")
            else:
                initial_parts.append(f"Let's review {subject}.\n\nStudy Guide:\n{guide_md}")
        initial_msg = "\n".join(initial_parts).strip() or "Let's begin."

        web_db.add_message(chat_id=chat_id, role="assistant", content=initial_msg)

        # Persist the guide so reopening is instant.
        try:
            schedule_item_id = int(sess.get("schedule_item_id") or 0)
        except Exception:
            schedule_item_id = 0
        if schedule_item_id > 0:
            try:
                assignment_id_val = sess.get("assignment_id")
                assignment_id_int = int(assignment_id_val) if assignment_id_val is not None else None
            except Exception:
                assignment_id_int = None

            try:
                web_db.upsert_revision_session(
                    user_id=int(user["id"]),
                    schedule_item_id=schedule_item_id,
                    assignment_id=assignment_id_int,
                    subject=subject,
                    scope=(str(sess.get("scope") or "").strip() or None),
                    duration_minutes=duration_minutes,
                    session_count=int(sess.get("session_count") or 1),
                    session_index=int(sess.get("session_index") or 1),
                    topics=topics_now,
                    all_topics=all_topics,
                    study_guide_md=guide_md,
                    chat_id=chat_id,
                )
            except Exception:
                current_app.logger.exception("Failed to cache generated guide")

        return jsonify(ok=True, reply=initial_msg, reply_html=web_markdown.render_markdown(initial_msg))

    @app.route("/api/revision/<int:chat_id>/send", methods=["POST"])
    def api_revision_send(chat_id: int):
        user = web_context.role_required("student")
        chat_row = web_db.get_chat(chat_id=chat_id, user_id=int(user["id"]))
        if not chat_row:
            return jsonify(ok=False, error="Chat not found"), 404

        payload: dict[str, Any] = {}
        if request.is_json:
            payload = request.get_json(silent=True) or {}
        else:
            payload = dict(request.form)

        text = (payload.get("message") or "").strip()
        use_web = _to_bool(payload.get("use_web"))

        upload_text: str | None = None
        upload_image_bytes: bytes | None = None
        upload_image_mime: str | None = None
        attachment_note = ""

        file = request.files.get("file")
        if file and file.filename:
            raw = file.read() or b""
            if len(raw) > 10 * 1024 * 1024:
                return jsonify(ok=False, error="File too large (max 10MB)."), 413
            try:
                res = web_uploads.process_upload(filename=file.filename, mime_type=file.mimetype, raw=raw)
            except Exception as e:
                return jsonify(ok=False, error=str(e)), 400

            if res.kind == "image":
                upload_image_bytes = res.image_bytes
                upload_image_mime = res.mime_type
                attachment_note = f"\n\n[Attachment: image {res.filename}]"
            else:
                upload_text = res.extracted_text
                attachment_note = f"\n\n[Attachment: {res.filename}]"

        if not text:
            return jsonify(ok=False, error="No message provided"), 400

        try:
            web_db.add_message(chat_id=chat_id, role="user", content=text + attachment_note)
            reply = gemini_reply_with_upload(
                user=user,
                chat_id=chat_id,
                user_text=text,
                use_web=use_web,
                upload_text=upload_text,
                upload_image_bytes=upload_image_bytes,
                upload_image_mime=upload_image_mime,
            )
            web_db.add_message(chat_id=chat_id, role="assistant", content=reply)
            reply_html = web_markdown.render_markdown(reply)
            return jsonify(ok=True, reply=reply, reply_html=reply_html)
        except Exception as e:
            current_app.logger.exception("Gemini reply failed in API")
            return jsonify(ok=False, error=f"Sorry — chat failed: {e}"), 500

    @app.route("/revision/<int:chat_id>/delete", methods=["POST"])
    def revision_delete(chat_id: int):
        user = web_context.role_required("student")
        chat_row = web_db.get_chat(chat_id=chat_id, user_id=int(user["id"]))
        if not chat_row:
            return jsonify(ok=False, error="Chat not found"), 404

        try:
            web_db.delete_chat(chat_id=chat_id, user_id=int(user["id"]))
            try:
                web_db.unlink_revision_sessions_for_deleted_chat(user_id=int(user["id"]), chat_id=chat_id)
            except Exception:
                current_app.logger.exception("Failed to unlink revision session cache from deleted chat")
            return jsonify(ok=True)
        except Exception as e:
            current_app.logger.exception("Failed to delete revision chat")
            return jsonify(ok=False, error=str(e)), 500
